### ISSUE TITLE
There is an issue about setup environment creation on AWS

### ISSUE THREAD

**Issue by jersonmartinez** [ACloudGuru-Resources/Course_Introduction_to_Ansible#5]
I'll show you the screenshot: 

![imagen](https://user-images.githubusercontent.com/7296281/112387569-8e587e00-8cb7-11eb-944c-6ba24e9e4050.png)

Template Setup Environment: https://github.com/ACloudGuru-Resources/Course_Introduction_to_Ansible/blob/master/02_02_Introduction_To_Ansible/setup-env.yml

AMI's doesn't exist: 

```yml
us-east-2:
      AMI: ami-02e680c4540db351e
us-west-2:
      AMI: ami-a0cfeed8
```

Could you provide me a solution to that?
